// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bigsmoke.proto

package loserpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectRankReq struct {
	RoundId              int64    `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Player               string   `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectRankReq) Reset()         { *m = CollectRankReq{} }
func (m *CollectRankReq) String() string { return proto.CompactTextString(m) }
func (*CollectRankReq) ProtoMessage()    {}
func (*CollectRankReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eef9e255e3858df, []int{0}
}

func (m *CollectRankReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRankReq.Unmarshal(m, b)
}
func (m *CollectRankReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRankReq.Marshal(b, m, deterministic)
}
func (m *CollectRankReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRankReq.Merge(m, src)
}
func (m *CollectRankReq) XXX_Size() int {
	return xxx_messageInfo_CollectRankReq.Size(m)
}
func (m *CollectRankReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRankReq.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRankReq proto.InternalMessageInfo

func (m *CollectRankReq) GetRoundId() int64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *CollectRankReq) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

type CollectRankRes struct {
	Rank                 int64    `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Part                 int64    `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectRankRes) Reset()         { *m = CollectRankRes{} }
func (m *CollectRankRes) String() string { return proto.CompactTextString(m) }
func (*CollectRankRes) ProtoMessage()    {}
func (*CollectRankRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eef9e255e3858df, []int{1}
}

func (m *CollectRankRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRankRes.Unmarshal(m, b)
}
func (m *CollectRankRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRankRes.Marshal(b, m, deterministic)
}
func (m *CollectRankRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRankRes.Merge(m, src)
}
func (m *CollectRankRes) XXX_Size() int {
	return xxx_messageInfo_CollectRankRes.Size(m)
}
func (m *CollectRankRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRankRes.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRankRes proto.InternalMessageInfo

func (m *CollectRankRes) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *CollectRankRes) GetPart() int64 {
	if m != nil {
		return m.Part
	}
	return 0
}

func init() {
	proto.RegisterType((*CollectRankReq)(nil), "loserpb.CollectRankReq")
	proto.RegisterType((*CollectRankRes)(nil), "loserpb.CollectRankRes")
}

func init() { proto.RegisterFile("bigsmoke.proto", fileDescriptor_1eef9e255e3858df) }

var fileDescriptor_1eef9e255e3858df = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xca, 0x4c, 0x2f,
	0xce, 0xcd, 0xcf, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xc9, 0x2f, 0x4e,
	0x2d, 0x2a, 0x48, 0x52, 0x72, 0xe6, 0xe2, 0x73, 0xce, 0xcf, 0xc9, 0x49, 0x4d, 0x2e, 0x09, 0x4a,
	0xcc, 0xcb, 0x0e, 0x4a, 0x2d, 0x14, 0x92, 0xe4, 0xe2, 0x28, 0xca, 0x2f, 0xcd, 0x4b, 0x89, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0x07, 0xf3, 0x3d, 0x53, 0x84, 0xc4, 0xb8,
	0xd8, 0x0a, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c,
	0x25, 0x0b, 0x34, 0x43, 0x8a, 0x85, 0x84, 0xb8, 0x58, 0x8a, 0x12, 0xf3, 0xb2, 0xa1, 0x06, 0x80,
	0xd9, 0x20, 0xb1, 0x82, 0xc4, 0xa2, 0x12, 0xb0, 0x5e, 0xe6, 0x20, 0x30, 0xdb, 0xc8, 0x9b, 0x8b,
	0x2d, 0x00, 0x6c, 0x86, 0x90, 0x23, 0x17, 0x37, 0x92, 0x19, 0x42, 0xe2, 0x7a, 0x50, 0x17, 0xea,
	0xa1, 0x3a, 0x4f, 0x0a, 0x87, 0x44, 0xb1, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x6f, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x17, 0x21, 0x84, 0xb4, 0xed, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	CollectRank(ctx context.Context, in *CollectRankReq, opts ...grpc.CallOption) (*CollectRankRes, error)
}

type playerClient struct {
	cc *grpc.ClientConn
}

func NewPlayerClient(cc *grpc.ClientConn) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) CollectRank(ctx context.Context, in *CollectRankReq, opts ...grpc.CallOption) (*CollectRankRes, error) {
	out := new(CollectRankRes)
	err := c.cc.Invoke(ctx, "/loserpb.Player/CollectRank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	CollectRank(context.Context, *CollectRankReq) (*CollectRankRes, error)
}

// UnimplementedPlayerServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServer struct {
}

func (*UnimplementedPlayerServer) CollectRank(ctx context.Context, req *CollectRankReq) (*CollectRankRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectRank not implemented")
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_CollectRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).CollectRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loserpb.Player/CollectRank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).CollectRank(ctx, req.(*CollectRankReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loserpb.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectRank",
			Handler:    _Player_CollectRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bigsmoke.proto",
}
